// full schema for a row extracted from the NCDX bhav copy CSVs
export interface HistoricalRecord {
  instrumentType: string;
  symbol: string;
  expiryDate: string;
  underlyingCommodity: string;
  strikePrice: number;
  optionType: string;
  exBasisDeliveryCentre: string;
  priceUnit: string;
  openingPrice: number;
  highPrice: number;
  lowPrice: number;
  closingPrice: number;
  quantityTradedToday: number;
  measure: string;
  noOfTrades: number;
  tradedValueInLacs: number;
  openInterest: number;
  lastTradedDate: string;
  date: string; // YYYY-MM-DD format
}

export const OILSEED_CROPS = [
  { key: 'soybeans', label: 'Soybeans' },
  { key: 'sunflower', label: 'Sunflower' },
  { key: 'castor', label: 'Castor' },
  { key: 'sesame', label: 'Sesame' },
];

// Build historical data with proper date handling
export const HISTORICAL_DATA: Record<string, HistoricalRecord[]> = {
  soybeans: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'MUMBAI',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4250,
      highPrice: 4300,
      lowPrice: 4200,
      closingPrice: 4250,
      quantityTradedToday: 2000,
      measure: 'MT',
      noOfTrades: 150,
      tradedValueInLacs: 850,
      openInterest: 5000,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'MUMBAI',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4310,
      highPrice: 4370,
      lowPrice: 4280,
      closingPrice: 4330,
      quantityTradedToday: 1950,
      measure: 'MT',
      noOfTrades: 160,
      tradedValueInLacs: 900,
      openInterest: 5200,
      lastTradedDate: '2026-02-12',
      date: '2026-02-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2026-04-20',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'MUMBAI',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4325,
      highPrice: 4385,
      lowPrice: 4300,
      closingPrice: 4360,
      quantityTradedToday: 2100,
      measure: 'MT',
      noOfTrades: 170,
      tradedValueInLacs: 920,
      openInterest: 5300,
      lastTradedDate: '2026-02-13',
      date: '2026-02-13',
    },
  ],
  sunflower: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'SUNFLOWER',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SUNFLOWER',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'KOLKATA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6800,
      highPrice: 6900,
      lowPrice: 6750,
      closingPrice: 6800,
      quantityTradedToday: 1200,
      measure: 'MT',
      noOfTrades: 90,
      tradedValueInLacs: 800,
      openInterest: 3000,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SUNFLOWER',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'SUNFLOWER',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'KOLKATA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6825,
      highPrice: 6925,
      lowPrice: 6800,
      closingPrice: 6900,
      quantityTradedToday: 1300,
      measure: 'MT',
      noOfTrades: 95,
      tradedValueInLacs: 830,
      openInterest: 3200,
      lastTradedDate: '2026-02-11',
      date: '2026-02-11',
    },
  ],
  castor: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6439,
      highPrice: 6500,
      lowPrice: 6439,
      closingPrice: 6450,
      quantityTradedToday: 4790,
      measure: 'MT',
      noOfTrades: 350,
      tradedValueInLacs: 3095.62,
      openInterest: 14365,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6508,
      highPrice: 6554,
      lowPrice: 6500,
      closingPrice: 6509,
      quantityTradedToday: 5395,
      measure: 'MT',
      noOfTrades: 470,
      tradedValueInLacs: 3519.12,
      openInterest: 15970,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-04-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6520,
      highPrice: 6570,
      lowPrice: 6510,
      closingPrice: 6550,
      quantityTradedToday: 4600,
      measure: 'MT',
      noOfTrades: 400,
      tradedValueInLacs: 3150,
      openInterest: 14200,
      lastTradedDate: '2026-02-11',
      date: '2026-02-11',
    },
  ],
  sesame: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'SESAME',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SESAMENUM',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'JAIPUR',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 1200,
      highPrice: 1250,
      lowPrice: 1150,
      closingPrice: 1220,
      quantityTradedToday: 450,
      measure: 'MT',
      noOfTrades: 35,
      tradedValueInLacs: 55,
      openInterest: 120,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SESAME',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'SESAMENUM',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'JAIPUR',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 1000,
      highPrice: 1050,
      lowPrice: 980,
      closingPrice: 1025,
      quantityTradedToday: 500,
      measure: 'MT',
      noOfTrades: 25,
      tradedValueInLacs: 51,
      openInterest: 200,
      lastTradedDate: '2026-02-11',
      date: '2026-02-11',
    },
  ],
};
