// full schema for a row extracted from the NCDX bhav copy CSVs
export interface HistoricalRecord {
  instrumentType: string;
  symbol: string;
  expiryDate: string;
  underlyingCommodity: string;
  strikePrice: number;
  optionType: string;
  exBasisDeliveryCentre: string;
  priceUnit: string;
  openingPrice: number;
  highPrice: number;
  lowPrice: number;
  closingPrice: number;
  quantityTradedToday: number;
  measure: string;
  noOfTrades: number;
  tradedValueInLacs: number;
  openInterest: number;
  lastTradedDate: string;
  date: string; // YYYY-MM-DD format
}

export const OILSEED_CROPS = [
  { key: 'soybeans', label: 'Soybeans' },
  { key: 'sunflower', label: 'Sunflower' },
  { key: 'castor', label: 'Castor' },
  { key: 'sesame', label: 'Sesame' },
];

// Extended crop data for better historical tracking
export const CROP_DATA_EXTENDED = {
  soybeans: {
    deliveryCentres: ['MUMBAI', 'INDORE', 'MADHYA PRADESH'],
    minPrice: 3800,
    maxPrice: 5000,
  },
  sunflower: {
    deliveryCentres: ['KOLKATA', 'KANDLA', 'HYDERABAD'],
    minPrice: 5500,
    maxPrice: 8500,
  },
  castor: {
    deliveryCentres: ['DEESA', 'JAIPUR', 'INDORE'],
    minPrice: 6200,
    maxPrice: 7500,
  },
  sesame: {
    deliveryCentres: ['JAIPUR', 'KOTA', 'JODHPUR'],
    minPrice: 8000,
    maxPrice: 12000,
  },
};

// Build historical data with proper date handling
export const HISTORICAL_DATA: Record<string, HistoricalRecord[]> = {
  soybeans: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'MUMBAI',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4250,
      highPrice: 4300,
      lowPrice: 4200,
      closingPrice: 4250,
      quantityTradedToday: 2000,
      measure: 'MT',
      noOfTrades: 150,
      tradedValueInLacs: 850,
      openInterest: 5000,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'MUMBAI',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4310,
      highPrice: 4370,
      lowPrice: 4280,
      closingPrice: 4330,
      quantityTradedToday: 1950,
      measure: 'MT',
      noOfTrades: 160,
      tradedValueInLacs: 900,
      openInterest: 5200,
      lastTradedDate: '2026-02-12',
      date: '2026-02-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2026-04-20',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'MUMBAI',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4325,
      highPrice: 4385,
      lowPrice: 4300,
      closingPrice: 4360,
      quantityTradedToday: 2100,
      measure: 'MT',
      noOfTrades: 170,
      tradedValueInLacs: 920,
      openInterest: 5300,
      lastTradedDate: '2026-02-13',
      date: '2026-02-13',
    },
    // Additional data from latest market feed
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2025-12-19',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'INDORE',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4380,
      highPrice: 4425,
      lowPrice: 4360,
      closingPrice: 4395,
      quantityTradedToday: 2250,
      measure: 'MT',
      noOfTrades: 145,
      tradedValueInLacs: 995,
      openInterest: 5450,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SOYBEAN',
      expiryDate: '2026-01-20',
      underlyingCommodity: 'SOYBEAN',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'INDORE',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 4410,
      highPrice: 4455,
      lowPrice: 4385,
      closingPrice: 4425,
      quantityTradedToday: 2180,
      measure: 'MT',
      noOfTrades: 168,
      tradedValueInLacs: 965,
      openInterest: 5680,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
  ],
  sunflower: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'SUNFLOWER',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SUNFLOWER',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'KOLKATA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6800,
      highPrice: 6900,
      lowPrice: 6750,
      closingPrice: 6800,
      quantityTradedToday: 1200,
      measure: 'MT',
      noOfTrades: 90,
      tradedValueInLacs: 800,
      openInterest: 3000,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SUNFLOWER',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'SUNFLOWER',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'KOLKATA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6825,
      highPrice: 6925,
      lowPrice: 6800,
      closingPrice: 6900,
      quantityTradedToday: 1300,
      measure: 'MT',
      noOfTrades: 95,
      tradedValueInLacs: 830,
      openInterest: 3200,
      lastTradedDate: '2026-02-11',
      date: '2026-02-11',
    },
    // New data from market feed 2025-12-12
    {
      instrumentType: 'FUTCOM',
      symbol: 'SUNFLOWER',
      expiryDate: '2025-12-19',
      underlyingCommodity: 'SUNFLOWER',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'KANDLA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 7180,
      highPrice: 7215,
      lowPrice: 7145,
      closingPrice: 7185,
      quantityTradedToday: 1650,
      measure: 'MT',
      noOfTrades: 112,
      tradedValueInLacs: 1185,
      openInterest: 3850,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SUNFLOWER',
      expiryDate: '2026-01-20',
      underlyingCommodity: 'SUNFLOWER',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'KANDLA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 7225,
      highPrice: 7265,
      lowPrice: 7190,
      closingPrice: 7230,
      quantityTradedToday: 1520,
      measure: 'MT',
      noOfTrades: 98,
      tradedValueInLacs: 1105,
      openInterest: 3650,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SUNFLOWER',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SUNFLOWER',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'KANDLA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 7270,
      highPrice: 7310,
      lowPrice: 7240,
      closingPrice: 7275,
      quantityTradedToday: 1380,
      measure: 'MT',
      noOfTrades: 85,
      tradedValueInLacs: 1008,
      openInterest: 3420,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
  ],
  castor: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6439,
      highPrice: 6500,
      lowPrice: 6439,
      closingPrice: 6450,
      quantityTradedToday: 4790,
      measure: 'MT',
      noOfTrades: 350,
      tradedValueInLacs: 3095.62,
      openInterest: 14365,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6508,
      highPrice: 6554,
      lowPrice: 6500,
      closingPrice: 6509,
      quantityTradedToday: 5395,
      measure: 'MT',
      noOfTrades: 470,
      tradedValueInLacs: 3519.12,
      openInterest: 15970,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-04-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6520,
      highPrice: 6570,
      lowPrice: 6510,
      closingPrice: 6550,
      quantityTradedToday: 4600,
      measure: 'MT',
      noOfTrades: 400,
      tradedValueInLacs: 3150,
      openInterest: 14200,
      lastTradedDate: '2026-02-11',
      date: '2026-02-11',
    },
    // New data from market feed 2025-12-12
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2025-12-19',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6973,
      highPrice: 6973,
      lowPrice: 6926,
      closingPrice: 6929,
      quantityTradedToday: 1840,
      measure: 'MT',
      noOfTrades: 183,
      tradedValueInLacs: 127.79,
      openInterest: 6810,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-01-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6991,
      highPrice: 6991,
      lowPrice: 6944,
      closingPrice: 6947,
      quantityTradedToday: 2730,
      measure: 'MT',
      noOfTrades: 304,
      tradedValueInLacs: 189.98,
      openInterest: 17160,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6875,
      highPrice: 6875,
      lowPrice: 6860,
      closingPrice: 6867,
      quantityTradedToday: 65,
      measure: 'MT',
      noOfTrades: 11,
      tradedValueInLacs: 4.46,
      openInterest: 430,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'CASTOR',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'CASTORSEEDNEW',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'DEESA',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 6970,
      highPrice: 6975,
      lowPrice: 6960,
      closingPrice: 6968,
      quantityTradedToday: 120,
      measure: 'MT',
      noOfTrades: 18,
      tradedValueInLacs: 8.36,
      openInterest: 850,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
  ],
  sesame: [
    {
      instrumentType: 'FUTCOM',
      symbol: 'SESAME',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SESAMENUM',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'JAIPUR',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 1200,
      highPrice: 1250,
      lowPrice: 1150,
      closingPrice: 1220,
      quantityTradedToday: 450,
      measure: 'MT',
      noOfTrades: 35,
      tradedValueInLacs: 55,
      openInterest: 120,
      lastTradedDate: '2026-02-10',
      date: '2026-02-10',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SESAME',
      expiryDate: '2026-03-20',
      underlyingCommodity: 'SESAMENUM',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'JAIPUR',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 1000,
      highPrice: 1050,
      lowPrice: 980,
      closingPrice: 1025,
      quantityTradedToday: 500,
      measure: 'MT',
      noOfTrades: 25,
      tradedValueInLacs: 51,
      openInterest: 200,
      lastTradedDate: '2026-02-11',
      date: '2026-02-11',
    },
    // New data from market feed 2025-12-12
    {
      instrumentType: 'FUTCOM',
      symbol: 'SESAME',
      expiryDate: '2025-12-19',
      underlyingCommodity: 'SESAMENUM',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'JAIPUR',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 11155,
      highPrice: 11155,
      lowPrice: 11155,
      closingPrice: 11155,
      quantityTradedToday: 0,
      measure: 'MT',
      noOfTrades: 0,
      tradedValueInLacs: 0,
      openInterest: 0,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SESAME',
      expiryDate: '2026-01-20',
      underlyingCommodity: 'SESAMENUM',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'JAIPUR',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 9535,
      highPrice: 9535,
      lowPrice: 9535,
      closingPrice: 9535,
      quantityTradedToday: 0,
      measure: 'MT',
      noOfTrades: 0,
      tradedValueInLacs: 0,
      openInterest: 0,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
    {
      instrumentType: 'FUTCOM',
      symbol: 'SESAME',
      expiryDate: '2026-02-20',
      underlyingCommodity: 'SESAMENUM',
      strikePrice: 0,
      optionType: 'XX',
      exBasisDeliveryCentre: 'JAIPUR',
      priceUnit: 'RS/QUINTAL',
      openingPrice: 9535,
      highPrice: 9535,
      lowPrice: 9535,
      closingPrice: 9535,
      quantityTradedToday: 0,
      measure: 'MT',
      noOfTrades: 0,
      tradedValueInLacs: 0,
      openInterest: 0,
      lastTradedDate: '2025-12-12',
      date: '2025-12-12',
    },
  ],
};
