import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';

export interface AgreementData {
  dealId:        string;
  farmerName:    string;
  farmerId?:     string;
  farmerLocation: string;
  dealerName:    string;
  dealerUid?:    string;
  crop:          string;
  quantity:      string;
  askPrice:      string;
  harvestDate?:  string;
  transportDate?: string;
  acceptedAt?:   string;   // formatted date string
  createdAt?:    string;
}

export async function downloadAgreementPdf(data: AgreementData) {
  const html = buildHTML(data);
  try {
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Save / Share Agreement',
        UTI: 'com.adobe.pdf',
      });
    } else {
      Alert.alert('Saved', `Agreement PDF saved at:\n${uri}`);
    }
  } catch {
    Alert.alert('Error', 'Could not generate the PDF. Please try again.');
  }
}

// ─── HTML template ────────────────────────────────────────────────────────────
function buildHTML(d: AgreementData): string {
  const today = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
  });

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #111; background: #fff; padding: 40px; }

    /* ── Header ── */
    .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #2D7A3A; padding-bottom: 16px; margin-bottom: 24px; }
    .logo   { font-size: 26px; font-weight: 800; color: #2D7A3A; letter-spacing: 0.5px; }
    .logo span { color: #1B2B1C; }
    .badge  { background: #2D7A3A; color: #fff; font-size: 11px; font-weight: 700; padding: 4px 10px; border-radius: 6px; letter-spacing: 1px; }

    /* ── Title block ── */
    .title  { text-align: center; margin-bottom: 24px; }
    .title h1 { font-size: 20px; font-weight: 800; color: #1B2B1C; text-transform: uppercase; letter-spacing: 1.5px; }
    .title p  { font-size: 12px; color: #555; margin-top: 4px; }

    /* ── Meta strip ── */
    .meta { display: flex; justify-content: space-between; background: #E8F5E9; border-radius: 8px; padding: 10px 16px; margin-bottom: 28px; font-size: 12px; color: #333; }
    .meta strong { color: #2D7A3A; }

    /* ── Section ── */
    .section { margin-bottom: 24px; }
    .section-title { font-size: 13px; font-weight: 700; color: #2D7A3A; text-transform: uppercase; letter-spacing: 0.8px; border-bottom: 1px solid #C8E6C9; padding-bottom: 6px; margin-bottom: 12px; }

    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
    .field { background: #FAFFF9; border: 1px solid #C8E6C9; border-radius: 8px; padding: 10px 14px; }
    .field label { font-size: 10px; color: #777; text-transform: uppercase; letter-spacing: 0.5px; display: block; margin-bottom: 3px; }
    .field span  { font-size: 14px; font-weight: 600; color: #1B2B1C; }

    .full { grid-column: span 2; }

    /* ── Deal highlight ── */
    .deal-price { background: #2D7A3A; color: #fff; border-radius: 10px; padding: 16px 20px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center; }
    .deal-price .label { font-size: 12px; opacity: 0.85; margin-bottom: 4px; }
    .deal-price .value { font-size: 22px; font-weight: 800; }

    /* ── Terms ── */
    .terms { font-size: 11.5px; color: #444; line-height: 1.75; background: #FFFDE7; border: 1px solid #FDD835; border-radius: 8px; padding: 14px 16px; margin-bottom: 28px; }
    .terms ol { padding-left: 18px; margin-top: 6px; }
    .terms li { margin-bottom: 4px; }

    /* ── Signatures ── */
    .sig-row { display: flex; justify-content: space-between; gap: 30px; margin-top: 8px; }
    .sig-box { flex: 1; border-top: 2px solid #333; padding-top: 8px; }
    .sig-box p { font-size: 12px; color: #444; }
    .sig-box strong { font-size: 13px; color: #1B2B1C; }
    .sig-space { height: 40px; }

    /* ── Footer ── */
    .footer { text-align: center; font-size: 10px; color: #aaa; margin-top: 32px; border-top: 1px solid #eee; padding-top: 12px; }
  </style>
</head>
<body>

  <!-- Header -->
  <div class="header">
    <div class="logo">Krishi<span>-Mitra</span></div>
    <div class="badge">OFFICIAL AGREEMENT</div>
  </div>

  <!-- Title -->
  <div class="title">
    <h1>Agricultural Deal Agreement</h1>
    <p>This agreement is auto-generated by Krishi-Mitra platform upon deal acceptance.</p>
  </div>

  <!-- Meta strip -->
  <div class="meta">
    <div>Agreement ID: <strong>${d.dealId.slice(0, 12).toUpperCase()}</strong></div>
    <div>Generated: <strong>${today}</strong></div>
    <div>Status: <strong style="color:#2D7A3A">✔ Accepted</strong></div>
  </div>

  <!-- Farmer details -->
  <div class="section">
    <div class="section-title">Farmer (Seller) Details</div>
    <div class="grid">
      <div class="field">
        <label>Farmer Name</label>
        <span>${d.farmerName}</span>
      </div>
      <div class="field">
        <label>Location</label>
        <span>${d.farmerLocation}</span>
      </div>
    </div>
  </div>

  <!-- Dealer details -->
  <div class="section">
    <div class="section-title">Dealer (Buyer) Details</div>
    <div class="grid">
      <div class="field">
        <label>Dealer Name</label>
        <span>${d.dealerName}</span>
      </div>
      <div class="field">
        <label>Dealer ID</label>
        <span>${(d.dealerUid ?? 'N/A').slice(0, 12).toUpperCase()}</span>
      </div>
    </div>
  </div>

  <!-- Deal terms -->
  <div class="section">
    <div class="section-title">Deal Details</div>
    <div class="grid">
      <div class="field">
        <label>Crop / Commodity</label>
        <span>${d.crop}</span>
      </div>
      <div class="field">
        <label>Quantity</label>
        <span>${d.quantity}</span>
      </div>
      <div class="field">
        <label>Harvest Date</label>
        <span>${d.harvestDate ?? '—'}</span>
      </div>
      <div class="field">
        <label>Ready for Transport</label>
        <span>${d.transportDate ?? '—'}</span>
      </div>
      <div class="field">
        <label>Deal Listed On</label>
        <span>${d.createdAt ?? '—'}</span>
      </div>
      <div class="field">
        <label>Accepted On</label>
        <span>${d.acceptedAt ?? today}</span>
      </div>
    </div>
  </div>

  <!-- Locked price highlight -->
  <div class="deal-price">
    <div>
      <div class="label">Agreed / Locked Price</div>
      <div class="value">${d.askPrice}</div>
    </div>
    <div style="font-size:36px; opacity:0.3">₹</div>
  </div>

  <!-- Terms -->
  <div class="terms">
    <strong>Terms &amp; Conditions:</strong>
    <ol>
      <li>The farmer agrees to supply the stated quantity of <strong>${d.crop}</strong> at the agreed price of <strong>${d.askPrice}</strong>.</li>
      <li>Delivery shall be ready for transport by <strong>${d.transportDate ?? 'the agreed date'}</strong>.</li>
      <li>Quality of produce must meet standard market norms; any deviation may be grounds for price renegotiation.</li>
      <li>This agreement is binding upon both parties once digitally confirmed on the Krishi-Mitra platform.</li>
      <li>Any disputes arising from this agreement shall be resolved amicably; failing which, they will be subject to the jurisdiction of local agricultural courts.</li>
      <li>Krishi-Mitra acts solely as a facilitator and bears no financial liability for non-fulfilment by either party.</li>
    </ol>
  </div>

  <!-- Signatures -->
  <div class="sig-row">
    <div class="sig-box">
      <div class="sig-space"></div>
      <p><strong>${d.farmerName}</strong></p>
      <p>Farmer / Seller</p>
    </div>
    <div class="sig-box">
      <div class="sig-space"></div>
      <p><strong>${d.dealerName}</strong></p>
      <p>Dealer / Buyer</p>
    </div>
    <div class="sig-box">
      <div class="sig-space"></div>
      <p><strong>Authorised Signatory</strong></p>
      <p>Krishi-Mitra Platform</p>
    </div>
  </div>

  <!-- Footer -->
  <div class="footer">
    This document was auto-generated by Krishi-Mitra · Agreement ID: ${d.dealId.slice(0, 12).toUpperCase()} · ${today}
  </div>

</body>
</html>
  `;
}
